events {}

http {
    include mime.types;

    server {
        listen 443 ssl;
        server_name melkess.42.fr;

        ssl_certificate     /etc/nginx/ssl/wordpress.crt;
        ssl_certificate_key /etc/nginx/ssl/wordpress.key;

        root /srv/www/wordpress;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass wordpress:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}